apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyurl-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyurl-service
  template:
    metadata:
      labels:
        app: tinyurl-service
    spec:
      containers:
        - name: tinyurl-service
          image: andrejev2006/tinyurl-service:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tinyurl-service
spec:
  selector:
    app: tinyurl-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
